name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: taggtimeline
          POSTGRES_PASSWORD: timeline
          POSTGRES_PORT: 5432
          POSTGRES_USER: timeline
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - uses: microsoft/variable-substitution@v1
      with:
        files: '**/appsettings.json'
      env:
        ConnectionString: "postgres://taggtimeline:timeline@postgres:5432/taggtimeline"
        DatabaseMigrationsEnabled: "true"
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
