name: postgres

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: music_test
          POSTGRES_PASSWORD: music
          POSTGRES_PORT: 5432
          POSTGRES_USER: music
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm i

      - name: Run jest
        run: npm run test
        env:
          DB_HOST: postgres
          DB_DATABASE: music_test